let tags = {
    "alternative" : {
        "title" : "alternative",
        "links" : [
            "https://sptfy.com/5hR9",
            "https://sptfy.com/dG9J",
            "https://sptfy.com/hSiQ",
            "https://sptfy.com/hSiW",
            "https://sptfy.com/hSiX",
            "https://sptfy.com/9u12",
            "https://sptfy.com/9u1N",
            "https://sptfy.com/ed3S",
            "https://sptfy.com/efQC",
            "https://sptfy.com/hSjT",
            "https://sptfy.com/9iKO",
            "https://sptfy.com/hH2O",
            "https://sptfy.com/duTK",
            "https://sptfy.com/5aP2",
            "https://sptfy.com/qUjL",
            "https://sptfy.com/a5Xw",
            "https://sptfy.com/9oXn",
            "https://sptfy.com/e9wQ",
            "https://sptfy.com/5ezs",
            "https://sptfy.com/9s4t",
            "https://sptfy.com/9s4p",
            "https://sptfy.com/5ijV",
            "https://sptfy.com/5tut",
            "https://sptfy.com/ivLQ",
        ],
    },
    
    "ambient" : {
        "title" : "ambient",
        "links" : [
            "https://sptfy.com/hSiJ",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/56p3",
        ],
    },
    
    "atmospheric" : {
        "title" : "atmospheric",
        "links" : [
            "https://sptfy.com/9u1m",
            "https://sptfy.com/dGaU",
            "https://sptfy.com/5qmL",
            "https://sptfy.com/i2fq",
            "https://sptfy.com/i6lG",
            "https://sptfy.com/9VA4",
            "https://sptfy.com/i58n",
        ],
    },
    
    "battle" : {
        "title" : "battle",
        "links" : [
            "https://sptfy.com/9u0y",
            "https://sptfy.com/9u1o",
            "https://sptfy.com/9u25",
            "https://sptfy.com/9u28",
        ],
    },
    
    "black" : {
        "title" : "black",
        "links" : [
            "https://sptfy.com/9u0o",
            "https://sptfy.com/hSiG",
            "https://sptfy.com/5hS9",
            "https://sptfy.com/9u1h",
            "https://sptfy.com/9u1i",
            "https://sptfy.com/9u1k",
            "https://sptfy.com/a69s",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/9u1p",
            "https://sptfy.com/9u1x",
            "https://sptfy.com/hSjJ",
            "https://sptfy.com/hSjM",
            "https://sptfy.com/hSjP",
            "https://sptfy.com/dGaU",
            "https://sptfy.com/9u23",
            "https://sptfy.com/lTbN",
            "https://sptfy.com/5c6z",
            "https://sptfy.com/5c6x",
            "https://sptfy.com/5hT9",
            "https://sptfy.com/5hTb",
            "https://sptfy.com/5i0c",
            "https://sptfy.com/9vX9",
            "https://sptfy.com/dP5d",
            "https://sptfy.com/5rwo",
            "https://sptfy.com/i6lG",
            "https://sptfy.com/e38A",
        ],
    },
    
    "blues" : {
        "title" : "blues",
        "links" : [
            "https://sptfy.com/hSiX",
            "https://sptfy.com/9Xg8",
        ],
    },
    
    "british" : {
        "title" : "british",
        "links" : [
            "https://sptfy.com/9u0E",
            "https://sptfy.com/hSiW",
            "https://sptfy.com/5e1v",
        ],
    },
    
    "celtic" : {
        "title" : "celtic",
        "links" : [
            "https://sptfy.com/hSiJ",
            "https://sptfy.com/5hTb",
            "https://sptfy.com/5no2",
        ],
    },
    
    "christian" : {
        "title" : "christian",
        "links" : [
            "https://sptfy.com/9u1N",
            "https://sptfy.com/5c6y",
            "https://sptfy.com/ej5K",
        ],
    },
    
    "classic-rock" : {
        "title" : "classic-rock",
        "links" : [
            "https://sptfy.com/hSiX",
            "https://sptfy.com/9u1g",
            "https://sptfy.com/hH2U",
            "https://sptfy.com/5hhl",
            "https://sptfy.com/m6pS",
        ],
    },
    
    "death" : {
        "title" : "death",
        "links" : [
            "https://sptfy.com/9u0k",
            "https://sptfy.com/9u0P",
            "https://sptfy.com/9u1x",
            "https://sptfy.com/hSjP",
            "https://sptfy.com/hSjS",
            "https://sptfy.com/iw3P",
            "https://sptfy.com/a69s",
            "https://sptfy.com/hSjU",
            "https://sptfy.com/hSjZ",
            "https://sptfy.com/9u21",
            "https://sptfy.com/9u23",
            "https://sptfy.com/dzOO",
            "https://sptfy.com/9ofC",
            "https://sptfy.com/9s4o",
            "https://sptfy.com/9ydT",
            "https://sptfy.com/qnXQ",
            "https://sptfy.com/dP7b",
        ],
    },
    
    "deathcore" : {
        "title" : "deathcore",
        "links" : [
            "https://sptfy.com/9u1C",
            "https://sptfy.com/9u21",
            "https://sptfy.com/9u23",
        ],
    },
    
    "doom" : {
        "title" : "doom",
        "links" : [
            "https://sptfy.com/9u0i",
            "https://sptfy.com/9u0k",
            "https://sptfy.com/hSiO",
            "https://sptfy.com/9u10",
            "https://sptfy.com/9u1x",
            "https://sptfy.com/hSjU",
            "https://sptfy.com/dGaU",
            "https://sptfy.com/9n6k",
            "https://sptfy.com/9ofC",
            "https://sptfy.com/9u2a",
            "https://sptfy.com/9s4o",
            "https://sptfy.com/9u52",
            "https://sptfy.com/5jtg",
            "https://sptfy.com/9wzO",
            "https://sptfy.com/9ydT",
            "https://sptfy.com/5qmL",
            "https://sptfy.com/i2fq",
            "https://sptfy.com/ie8u",
        ],
    },
    
    "dwarf-pirate" : {
        "title" : "dwarf-pirate",
        "links" : [
            "https://sptfy.com/hSiY",
            "https://sptfy.com/dGaT",
            "https://sptfy.com/9iKS",
            "https://sptfy.com/5r65",
        ],
    },
    
    "emo-core" : {
        "title" : "emo-core",
        "links" : [
            "https://sptfy.com/9u0d",
            "https://sptfy.com/9iKO",
        ],
    },
    
    "epic" : {
        "title" : "epic",
        "links" : [
            "https://sptfy.com/5hR7",
            "https://sptfy.com/9u0u",
            "https://sptfy.com/9u0x",
            "https://sptfy.com/9u1p",
            "https://sptfy.com/dGaU",
            "https://sptfy.com/duTT",
            "https://sptfy.com/duTP",
            "https://sptfy.com/9ivQ",
            "https://sptfy.com/dIdQ",
            "https://sptfy.com/5oD8",
        ],
    },
    
    "euro-dance" : {
        "title" : "euro-dance",
        "links" : [
            "https://sptfy.com/9u1f",
            "https://sptfy.com/9u1w",
            "https://sptfy.com/hSjT",
            "https://sptfy.com/9iKS",
            "https://sptfy.com/9nFN",
            "https://sptfy.com/5du2",
            "https://sptfy.com/5jH1",
            "https://sptfy.com/e44a",
        ],
    },
    
    "extreme" : {
        "title" : "extreme",
        "links" : [
            "https://sptfy.com/9u0P",
            "https://sptfy.com/dG9X",
            "https://sptfy.com/9u1s",
            "https://sptfy.com/ej5K",
            "https://sptfy.com/hSjJ",
            "https://sptfy.com/5hT9",
        ],
    },
    
    "female" : {
        "title" : "female",
        "links" : [
            "https://sptfy.com/9u0n",
            "https://sptfy.com/hSiO",
            "https://sptfy.com/hSiR",
            "https://sptfy.com/9u1f",
            "https://sptfy.com/9u1w",
            "https://sptfy.com/5hSx",
            "https://sptfy.com/dGaM",
            "https://sptfy.com/hSjT",
            "https://sptfy.com/dGaU",
            "https://sptfy.com/duTT",
            "https://sptfy.com/574h",
            "https://sptfy.com/efQC",
            "https://sptfy.com/eb6p",
            "https://sptfy.com/9TE5",
            "https://sptfy.com/9nFN",
            "https://sptfy.com/9ofC",
            "https://sptfy.com/5du2",
            "https://sptfy.com/9u28",
            "https://sptfy.com/9s4o",
            "https://sptfy.com/9u52",
            "https://sptfy.com/9u5d",
            "https://open.spotify.com/album/2WzWIsWJtI5n2PWK79PxGC",
            "https://sptfy.com/5jtk",
            "https://sptfy.com/5jH1",
            "https://sptfy.com/9vX9",
            "https://sptfy.com/dIdQ",
            "https://sptfy.com/9yl1",
            "https://sptfy.com/5noU",
            "https://sptfy.com/ed3S",
            "https://sptfy.com/5tut",
            "https://sptfy.com/5yhu",
            "https://sptfy.com/e44a",
        ],
    },

    "folk" : {
        "title" : "folk",
        "links" : [
            "https://sptfy.com/5hR7",
            "https://sptfy.com/9u0t",
            "https://sptfy.com/9u0x",
            "https://sptfy.com/hSiG",
            "https://sptfy.com/a4fR",
            "https://sptfy.com/dG9F",
            "https://sptfy.com/9Xg4",
            "https://sptfy.com/ejVF",
            "https://sptfy.com/hSiJ",
            "https://sptfy.com/hSiY",
            "https://sptfy.com/dGaT",
            "https://sptfy.com/dGaV",
            "https://sptfy.com/9u20",
            "https://sptfy.com/9u25",
            "https://sptfy.com/9u27",
            "https://sptfy.com/5R2p",
            "https://sptfy.com/9iKS",
            "https://sptfy.com/9n6u",
            "https://sptfy.com/5c6z",
            "https://sptfy.com/5c6x",
            "https://sptfy.com/9u28",
            "https://sptfy.com/5hTb",
            "https://sptfy.com/9u2e",
            "https://sptfy.com/5no2",
            "https://sptfy.com/5oD8",
            "https://sptfy.com/i0aq",
            "https://sptfy.com/i0fL",
            "https://sptfy.com/5r48",
            "https://sptfy.com/5r65",
            "https://sptfy.com/5rwo",
            "https://sptfy.com/iaBd",
            "https://sptfy.com/icnJ",
            "https://sptfy.com/e38A",
            "https://sptfy.com/ej6w",
        ],
    },
    
    "garage" : {
        "title" : "garage",
        "links" : [
            "https://sptfy.com/hSiQ",
        ],
    },
    
    "gothic" : {
        "title" : "gothic",
        "links" : [
            "https://sptfy.com/9u0i",
            "https://sptfy.com/hSjU",
            "https://sptfy.com/duTT",
            "https://sptfy.com/9iKO",
            "https://sptfy.com/9u28",
            "https://sptfy.com/9s4t",
            "https://sptfy.com/9s4o",
            "https://sptfy.com/5hho",
            "https://sptfy.com/9VA4",
            "https://sptfy.com/9u52",
            "https://sptfy.com/a2d7",
            "https://sptfy.com/5jtg",
            "https://sptfy.com/5jH1",
            "https://sptfy.com/9TE5",
            "https://sptfy.com/ed3S",
            "https://sptfy.com/9ydT",
            "https://sptfy.com/9yl1",
            "https://sptfy.com/qnXQ",
            "https://sptfy.com/5qmL",
            "https://sptfy.com/dP5d",
            "https://sptfy.com/i2fq",
            "https://sptfy.com/5yhu",
            "https://sptfy.com/5zcQ",
        ],
    },
    
    "groove" : {
        "title" : "groove",
        "links" : [
            "https://sptfy.com/9u1v",
            "https://sptfy.com/9u1Z",
            "https://sptfy.com/9iKL",
            "https://sptfy.com/5urr",
        ],
    },
    
    "grunge" : {
        "title" : "grunge",
        "links" : [
            "https://sptfy.com/5tut",
        ],
    },
    
    "hardcore" : {
        "title" : "hardcore",
        "links" : [
            "https://sptfy.com/hSjZ",
            "https://sptfy.com/dGb0",
            "https://sptfy.com/duTR",
            "https://sptfy.com/duTK",
            "https://sptfy.com/ej5K",
            "https://sptfy.com/5j48",
            "https://sptfy.com/9w70",
            "https://sptfy.com/5urr",
            "https://sptfy.com/9KuX",
        ],
    },
    
    "hard-rock" : {
        "title" : "hard-rock",
        "links" : [
            "https://sptfy.com/dGaO",
            "https://sptfy.com/9u1N",
            "https://sptfy.com/5hhl",
            "https://sptfy.com/iugS",
            "https://sptfy.com/a5Xw",
            "https://sptfy.com/efQC",
            "https://sptfy.com/qlqW",
            "https://sptfy.com/5uvt",
        ],
    },
    
    "heavy" : {
        "title" : "heavy",
        "links" : [
            "https://sptfy.com/9u0f",
            "https://sptfy.com/9u0y",
            "https://sptfy.com/9u1g",
            "https://sptfy.com/hH2U",
            "https://sptfy.com/iugS",
            "https://sptfy.com/dzOO",
            "https://sptfy.com/hNfp",
            "https://sptfy.com/5du4",
            "https://sptfy.com/el8l",
            "https://sptfy.com/9s4r",
            "https://sptfy.com/5hhp",
            "https://sptfy.com/a5Xw",
            "https://sptfy.com/5hhk",
            "https://sptfy.com/eb6p",
            "https://sptfy.com/9u2g",
            "https://sptfy.com/9vQ8",
            "https://sptfy.com/m6pS",
            "https://sptfy.com/5k3O",
            "https://sptfy.com/qlqW",
            "https://sptfy.com/5noU",
            "https://sptfy.com/dS5m",
            "https://sptfy.com/5uvt",
        ],
    },
    
    "indie" : {
        "title" : "indie",
        "links" : [
            "https://sptfy.com/9u0E",
        ],
    },
    
    "industrial" : {
        "title" : "industrial",
        "links" : [
            "https://sptfy.com/9u0z",
            "https://sptfy.com/9u0A",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/5j9p",
            "https://sptfy.com/i58n",
            "https://sptfy.com/ec1d",
        ],
    },
    
    "instrumental" : {
        "title" : "instrumental",
        "links" : [
            "https://sptfy.com/hSiJ",
            "https://sptfy.com/56p3",
        ],
    },
    
    "medieval" : {
        "title" : "medieval",
        "links" : [
            "https://sptfy.com/9u20",
        ],
    },
    
    "melancholic" : {
        "title" : "melancholic",
        "links" : [
            "https://sptfy.com/9ydT",
        ],
    },
    
    "melodic" : {
        "title" : "melodic",
        "links" : [
            "https://sptfy.com/9u1p",
            "https://sptfy.com/dGb0",
            "https://sptfy.com/hH2U",
            "https://sptfy.com/duTR",
            "https://sptfy.com/9ivQ",
            "https://sptfy.com/el8l",
            "https://sptfy.com/574h",
            "https://sptfy.com/hNfp",
            "https://sptfy.com/5du4",
            "https://sptfy.com/5du2",
            "https://sptfy.com/9s4t",
            "https://sptfy.com/9s4o",
            "https://sptfy.com/5hho",
            "https://sptfy.com/9u2g",
            "https://sptfy.com/9u5d",
            "https://sptfy.com/e44a",
            "https://sptfy.com/qlqW",
            "https://sptfy.com/5rwo",
            "https://sptfy.com/ie8u",
        ],
    },
    
    "melodic-death" : {
        "title" : "melodic-death",
        "links" : [
            "https://sptfy.com/5hR8",
            "https://sptfy.com/5hR9",
            "https://sptfy.com/9u0c",
            "https://sptfy.com/9u0q",
            "https://sptfy.com/9u0s",
            "https://sptfy.com/9u0t",
            "https://sptfy.com/9u0u",
            "https://sptfy.com/9u0x",
            "https://sptfy.com/9u0y",
            "https://sptfy.com/a69s",
            "https://sptfy.com/9u0A",
            "https://sptfy.com/hSiG",
            "https://sptfy.com/dG9F",
            "https://sptfy.com/iw3P",
            "https://sptfy.com/dG9K",
            "https://sptfy.com/dG9L",
            "https://sptfy.com/hSiO",
            "https://sptfy.com/hSiR",
            "https://sptfy.com/5R2p",
            "https://sptfy.com/9u10",
            "https://sptfy.com/5hS2",
            "https://sptfy.com/5hS9",
            "https://sptfy.com/9u1h",
            "https://sptfy.com/9u1i",
            "https://sptfy.com/9u1k",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/hSjJ",
            "https://sptfy.com/hSjM",
            "https://sptfy.com/hSjN",
            "https://sptfy.com/dGaV",
            "https://sptfy.com/hSk0",
            "https://sptfy.com/9u25",
            "https://sptfy.com/9u27",
            "https://sptfy.com/duTP",
            "https://sptfy.com/9iKL",
            "https://sptfy.com/9n6k",
            "https://sptfy.com/5c6x",
            "https://sptfy.com/5e1s",
            "https://sptfy.com/9u29",
            "https://sptfy.com/9u2a",
            "https://sptfy.com/5hT9",
            "https://sptfy.com/9u2c",
            "https://sptfy.com/hR31",
            "https://sptfy.com/9sKW",
            "https://sptfy.com/5i0c",
            "https://sptfy.com/5i0i",
            "https://sptfy.com/5jtg",
            "https://sptfy.com/9vK1",
            "https://sptfy.com/hU80",
            "https://sptfy.com/9w5X",
            "https://sptfy.com/9wzO",
            "https://sptfy.com/9VA4",
            "https://sptfy.com/a2d7",
            "https://sptfy.com/5mC6",
            "https://sptfy.com/mbbS",
            "https://sptfy.com/i0aq",
            "https://sptfy.com/i0ar",
            "https://sptfy.com/i2fq",
            "https://sptfy.com/5zcQ",
            "https://sptfy.com/a4fR",
            "https://sptfy.com/e38A",
            "https://sptfy.com/ej6w",
        ],
    },

    "metal" : {
        "title" : "metal",
        "links" : [
            "https://sptfy.com/5hR7",
            "https://sptfy.com/e44a",
            "https://sptfy.com/5hR8",
            "https://sptfy.com/5hR9",
            "https://sptfy.com/9Xg4",
            "https://sptfy.com/qUjL",
            "https://sptfy.com/a2d7",
            "https://sptfy.com/el8l",
            "https://sptfy.com/ejVF",
            "https://sptfy.com/ed3S",
            "https://sptfy.com/iugS",
            "https://sptfy.com/a4fR",
            "https://sptfy.com/5R2p",
            "https://sptfy.com/ej6w",
            "https://sptfy.com/ec1d",
            "https://sptfy.com/9u0c",
            "https://sptfy.com/iw3P",
            "https://sptfy.com/9u0f",
            "https://sptfy.com/9u0h",
            "https://sptfy.com/9u0i",
            "https://sptfy.com/9u0k",
            "https://sptfy.com/9VA4",
            "https://sptfy.com/eb6p",
            "https://sptfy.com/9u0l",
            "https://sptfy.com/9u0n",
            "https://sptfy.com/9u0o",
            "https://sptfy.com/9u0q",
            "https://sptfy.com/9TE5",
            "https://sptfy.com/a5Xw",
            "https://sptfy.com/9u0s",
            "https://sptfy.com/9u0t",
            "https://sptfy.com/9u0u",
            "https://sptfy.com/9u0x",
            "https://sptfy.com/9u0y",
            "https://sptfy.com/9u0z",
            "https://sptfy.com/9u0A",
            "https://sptfy.com/a69s",
            "https://sptfy.com/9u0B",
            "https://sptfy.com/hSiG",
            "https://sptfy.com/dG9F",
            "https://sptfy.com/dG9K",
            "https://sptfy.com/dG9L",
            "https://sptfy.com/hSiO",
            "https://sptfy.com/hSiR",
            "https://sptfy.com/9u0P",
            "https://sptfy.com/hSiY",
            "https://sptfy.com/dG9X",
            "https://sptfy.com/dGa0",
            "https://sptfy.com/9u10",
            "https://sptfy.com/9u12",
            "https://sptfy.com/5hS2",
            "https://sptfy.com/5hS9",
            "https://sptfy.com/9u1d",
            "https://sptfy.com/9u1f",
            "https://sptfy.com/9u1g",
            "https://sptfy.com/9u1h",
            "https://sptfy.com/9u1i",
            "https://sptfy.com/9u1k",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/9u1o",
            "https://sptfy.com/9u1p",
            "https://sptfy.com/9u1s",
            "https://sptfy.com/9u1v",
            "https://sptfy.com/9u1w",
            "https://sptfy.com/9u1x",
            "https://sptfy.com/5hSx",
            "https://sptfy.com/9u1C",
            "https://sptfy.com/hSjJ",
            "https://sptfy.com/hSjM",
            "https://sptfy.com/dGaM",
            "https://sptfy.com/hSjP",
            "https://sptfy.com/dGaO",
            "https://sptfy.com/hSjS",
            "https://sptfy.com/hSjT",
            "https://sptfy.com/hSjU",
            "https://sptfy.com/dGaT",
            "https://sptfy.com/dGaU",
            "https://sptfy.com/dGaV",
            "https://sptfy.com/hSjZ",
            "https://sptfy.com/hSk0",
            "https://sptfy.com/dGb0",
            "https://sptfy.com/9u1Z",
            "https://sptfy.com/9u20",
            "https://sptfy.com/9u21",
            "https://sptfy.com/9u23",
            "https://sptfy.com/9u25",
            "https://sptfy.com/9u27",
            "https://sptfy.com/9iKS",
            "https://sptfy.com/duTT",
            "https://sptfy.com/hH2U",
            "https://sptfy.com/duTP",
            "https://sptfy.com/9iKL",
            "https://sptfy.com/hH2O",
            "https://sptfy.com/duTK",
            "https://sptfy.com/lTbN",
            "https://sptfy.com/9ivQ",
            "https://sptfy.com/574h",
            "https://sptfy.com/5aP2",
            "https://sptfy.com/9mY3",
            "https://sptfy.com/9n6k",
            "https://sptfy.com/9n6u",
            "https://sptfy.com/9nFN",
            "https://sptfy.com/dzOO",
            "https://sptfy.com/9ofC",
            "https://sptfy.com/5c6z",
            "https://sptfy.com/5c6y",
            "https://sptfy.com/5c6x",
            "https://sptfy.com/hNfp",
            "https://sptfy.com/5du4",
            "https://sptfy.com/5du2",
            "https://sptfy.com/5du3",
            "https://sptfy.com/9u28",
            "https://sptfy.com/9u29",
            "https://sptfy.com/9u2a",
            "https://sptfy.com/5hT9",
            "https://sptfy.com/9u2c",
            "https://sptfy.com/5hTb",
            "https://sptfy.com/9s4t",
            "https://sptfy.com/9s4r",
            "https://sptfy.com/9s4o",
            "https://sptfy.com/hR31",
            "https://sptfy.com/9sKW",
            "https://sptfy.com/5hhp",
            "https://sptfy.com/5hho",
            "https://sptfy.com/5hhn",
            "https://sptfy.com/5hhk",
            "https://sptfy.com/9u2e",
            "https://sptfy.com/9u2g",
            "https://sptfy.com/9u52",
            "https://sptfy.com/9u5d",
            "https://sptfy.com/5i0c",
            "https://sptfy.com/5i0i",
            "https://sptfy.com/5ijV",
            "https://sptfy.com/5j9p",
            "https://open.spotify.com/album/2WzWIsWJtI5n2PWK79PxGC",
            "https://sptfy.com/5jtg",
            "https://sptfy.com/5jtk",
            "https://sptfy.com/9vK1",
            "https://sptfy.com/hU80",
            "https://sptfy.com/5jH1",
            "https://sptfy.com/9vQ8",
            "https://sptfy.com/9vX9",
            "https://sptfy.com/m6pS",
            "https://sptfy.com/dIdQ",
            "https://sptfy.com/9w5X",
            "https://sptfy.com/5k3O",
            "https://sptfy.com/9wzO",
            "https://sptfy.com/hV5P",
            "https://sptfy.com/9ydT",
            "https://sptfy.com/5mC6",
            "https://sptfy.com/qlqW",
            "https://sptfy.com/5no2",
            "https://sptfy.com/5noU",
            "https://sptfy.com/5ocH",
            "https://sptfy.com/hZ2t",
            "https://sptfy.com/mbbS",
            "https://sptfy.com/5oD8",
            "https://sptfy.com/qnXQ",
            "https://sptfy.com/i0aq",
            "https://sptfy.com/i0ar",
            "https://sptfy.com/i0fL",
            "https://sptfy.com/5q3g",
            "https://sptfy.com/5qmL",
            "https://sptfy.com/dP5d",
            "https://sptfy.com/dP7b",
            "https://sptfy.com/5r48",
            "https://sptfy.com/5r65",
            "https://sptfy.com/5rwo",
            "https://sptfy.com/i2fq",
            "https://sptfy.com/dS5m",
            "https://sptfy.com/i6lG",
            "https://sptfy.com/i58n",
            "https://sptfy.com/5uvt",
            "https://sptfy.com/5urr",
            "https://sptfy.com/5yhu",
            "https://sptfy.com/9KuX",
            "https://sptfy.com/5zcQ",
            "https://sptfy.com/iaBd",
            "https://sptfy.com/e0ed",
            "https://sptfy.com/icnJ",
            "https://sptfy.com/ie8u",
            "https://sptfy.com/e38A",
        ],
    },
    
    "metalcore" : {
        "title" : "metalcore",
        "links" : [
            "https://sptfy.com/5hR9",
            "https://sptfy.com/9u0l",
            "https://sptfy.com/9u0P",
            "https://sptfy.com/e7Bi",
            "https://sptfy.com/9u12",
            "https://sptfy.com/9u1q",
            "https://sptfy.com/ej5K",
            "https://sptfy.com/9u1C",
            "https://sptfy.com/hSjJ",
            "https://sptfy.com/hSjN",
            "https://sptfy.com/dGaO",
            "https://sptfy.com/hSjZ",
            "https://sptfy.com/dGb0",
            "https://sptfy.com/9u1Z",
            "https://sptfy.com/9u21",
            "https://sptfy.com/hH2O",
            "https://sptfy.com/5aP2",
            "https://sptfy.com/5c6y",
            "https://sptfy.com/5e1s",
            "https://sptfy.com/9s4t",
            "https://sptfy.com/5i0i",
            "https://sptfy.com/5j48",
            "https://sptfy.com/9w70",
            "https://sptfy.com/5mC6",
            "https://sptfy.com/mbbS",
            "https://sptfy.com/5urr",
            "https://sptfy.com/9KuX",
        ],
    },
    
    "modern" : {
        "title" : "modern",
        "links" : [
            "https://sptfy.com/5hR9",
            "https://sptfy.com/9u0A",
            "https://sptfy.com/5du4",
            "https://sptfy.com/5du2",
            "https://sptfy.com/9u29",
            "https://sptfy.com/5mC6",
            "https://sptfy.com/mbbS",
        ],
    },
    
    "new2019" : {
        "title" : "new2019",
        "links" : [
            "https://sptfy.com/5hR9",
            "https://sptfy.com/9u0c",
            "https://sptfy.com/9u0d",
            "https://sptfy.com/9u0f",
            "https://sptfy.com/9u0h",
            "https://sptfy.com/9u0i",
            "https://sptfy.com/9u0k",
            "https://sptfy.com/9u0l",
            "https://sptfy.com/9u0n",
            "https://sptfy.com/9u0o",
            "https://sptfy.com/9u0q",
            "https://sptfy.com/9u0s",
            "https://sptfy.com/9u0t",
            "https://sptfy.com/9u0u",
            "https://sptfy.com/9u0x",
            "https://sptfy.com/9u0y",
            "https://sptfy.com/9u0z",
            "https://sptfy.com/9u0A",
            "https://sptfy.com/9u0B",
            "https://sptfy.com/hSiG",
            "https://sptfy.com/dG9F",
            "https://sptfy.com/9u0E",
            "https://sptfy.com/hSiJ",
            "https://sptfy.com/dG9J",
            "https://sptfy.com/dG9K",
            "https://sptfy.com/hSiQ",
            "https://sptfy.com/hSiR",
            "https://sptfy.com/9u0P",
            "https://sptfy.com/hSiW",
            "https://sptfy.com/hSiY",
            "https://sptfy.com/dG9X",
            "https://sptfy.com/dGa0",
            "https://sptfy.com/9u10",
            "https://sptfy.com/9u12",
            "https://sptfy.com/5hS2",
            "https://sptfy.com/5hS9",
            "https://sptfy.com/9u1d",
            "https://sptfy.com/9u1f",
            "https://sptfy.com/9u1g",
            "https://sptfy.com/9u1i",
            "https://sptfy.com/9u1k",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/9u1p",
            "https://sptfy.com/9u1q",
            "https://sptfy.com/9u1x",
            "https://sptfy.com/hH2O",
            "https://sptfy.com/duTK",
            "https://sptfy.com/5hT9",
            "https://sptfy.com/9s4t",
            "https://sptfy.com/5hhp",
            "https://sptfy.com/9u2e",
            "https://sptfy.com/5ijV",
            "https://open.spotify.com/album/2WzWIsWJtI5n2PWK79PxGC",
            "https://sptfy.com/dIdQ",
            "https://sptfy.com/5k3O",
            "https://sptfy.com/9wzO",
            "https://sptfy.com/mbbS",
            "https://sptfy.com/a2d7",
            "https://sptfy.com/5oD8",
            "https://sptfy.com/i0aq",
            "https://sptfy.com/i0fL",
            "https://sptfy.com/5rwo",
            "https://sptfy.com/i58n",
        ],
    },
    
    "new2020" : {
        "title" : "new2020",
        "links" : [
            "https://sptfy.com/9u1o",
            "https://sptfy.com/9u1s",
            "https://sptfy.com/9u1v",
            "https://sptfy.com/9u1w",
            "https://sptfy.com/5hSx",
            "https://sptfy.com/9u1C",
            "https://sptfy.com/hSjJ",
            "https://sptfy.com/ec1d",
            "https://sptfy.com/hSjM",
            "https://sptfy.com/a5Xw",
            "https://sptfy.com/hSjN",
            "https://sptfy.com/iw3P",
            "https://sptfy.com/dGaM",
            "https://sptfy.com/hSjP",
            "https://sptfy.com/dGaO",
            "https://sptfy.com/9u1N",
            "https://sptfy.com/hSjS",
            "https://sptfy.com/a69s",
            "https://sptfy.com/hSjT",
            "https://sptfy.com/hSjU",
            "https://sptfy.com/dGaT",
            "https://sptfy.com/dGaU",
            "https://sptfy.com/dGaV",
            "https://sptfy.com/hSjZ",
            "https://sptfy.com/hSk0",
            "https://sptfy.com/dGb0",
            "https://sptfy.com/9u1Z",
            "https://sptfy.com/9u20",
            "https://sptfy.com/9u21",
            "https://sptfy.com/9u23",
            "https://sptfy.com/9u25",
            "https://sptfy.com/9iKS",
            "https://sptfy.com/duTT",
            "https://sptfy.com/hH2U",
            "https://sptfy.com/duTR",
            "https://sptfy.com/9iKO",
            "https://sptfy.com/duTP",
            "https://sptfy.com/9iKL",
            "https://sptfy.com/lTbN",
            "https://sptfy.com/9ivQ",
            "https://sptfy.com/56p3",
            "https://sptfy.com/574h",
            "https://sptfy.com/5aP2",
            "https://sptfy.com/9mY3",
            "https://sptfy.com/9n6k",
            "https://sptfy.com/9n6u",
            "https://sptfy.com/9nFN",
            "https://sptfy.com/dzOO",
            "https://sptfy.com/9ofC",
            "https://sptfy.com/5c6z",
            "https://sptfy.com/5c6y",
            "https://sptfy.com/5c6x",
            "https://sptfy.com/9oXn",
            "https://sptfy.com/hNfp",
            "https://sptfy.com/5du4",
            "https://sptfy.com/5du2",
            "https://sptfy.com/5du3",
            "https://sptfy.com/5e1s",
            "https://sptfy.com/5e1v",
            "https://sptfy.com/5ezs",
            "https://sptfy.com/9u28",
            "https://sptfy.com/9u29",
            "https://sptfy.com/9u2a",
            "https://sptfy.com/9u2c",
            "https://sptfy.com/5hTb",
            "https://sptfy.com/9s4r",
            "https://sptfy.com/9s4p",
            "https://sptfy.com/9s4o",
            "https://sptfy.com/hR31",
            "https://sptfy.com/9sKW",
            "https://sptfy.com/5hho",
            "https://sptfy.com/5hhn",
            "https://sptfy.com/5hhl",
            "https://sptfy.com/5hhk",
            "https://sptfy.com/9u2g",
            "https://sptfy.com/9u52",
            "https://sptfy.com/9u5d",
            "https://sptfy.com/5i0c",
            "https://sptfy.com/5i0i",
            "https://sptfy.com/hT6R",
            "https://sptfy.com/5j48",
            "https://sptfy.com/5j9p",
            "https://sptfy.com/5jtg",
            "https://sptfy.com/5jtk",
            "https://sptfy.com/9vDD",
            "https://sptfy.com/9vK1",
            "https://sptfy.com/hU80",
            "https://sptfy.com/5jH1",
            "https://sptfy.com/9vQ8",
            "https://sptfy.com/9vX9",
            "https://sptfy.com/a4fR",
            "https://sptfy.com/m6pS",
            "https://sptfy.com/9w70",
            "https://sptfy.com/9ydT",
            "https://sptfy.com/9yl1",
            "https://sptfy.com/5mC6",
            "https://sptfy.com/qlqW",
            "https://sptfy.com/5nnl",
            "https://sptfy.com/5no2",
            "https://sptfy.com/5noU",
            "https://sptfy.com/hZ2t",
            "https://sptfy.com/dP7b",
            "https://sptfy.com/i2fq",
            "https://sptfy.com/5uvt",
            "https://sptfy.com/5urr",
        ],
    },
    
    "new2021" : {
        "title" : "new2021",
        "links" : [
            "https://sptfy.com/5ocH",
            "https://sptfy.com/qnXQ",
            "https://sptfy.com/5q3g",
            "https://sptfy.com/5r48",
            "https://sptfy.com/iugS",
            "https://sptfy.com/5r65",
            "https://sptfy.com/5tut",
            "https://sptfy.com/ejVF",
            "https://sptfy.com/e9wQ",
            "https://sptfy.com/efQC",
            "https://sptfy.com/qUjL",
            "https://sptfy.com/eb6p",
            "https://sptfy.com/9Xg4",
            "https://sptfy.com/el8l",
            "https://sptfy.com/9Xg8",
            "https://sptfy.com/ed3S",
            "https://sptfy.com/dS5m",
            "https://sptfy.com/i6lG",
            "https://sptfy.com/9VA4",
            "https://sptfy.com/5R2p",
            "https://sptfy.com/9Xd2",
            "https://sptfy.com/5yhu",
            "https://sptfy.com/e7Bi",
            "https://sptfy.com/9KuX",
            "https://sptfy.com/iaBd",
            "https://sptfy.com/9TE5",
            "https://sptfy.com/e0ed",
            "https://sptfy.com/icnJ",
            "https://sptfy.com/ie8u",
            "https://sptfy.com/e38A",
            "https://sptfy.com/e44a",
            "https://sptfy.com/ivLQ",
            "https://sptfy.com/ej6w",
            "https://sptfy.com/ej5K",
        ],
    },
    
    "nu" : {
        "title" : "nu",
        "links" : [
            "https://sptfy.com/duTK",
            "https://sptfy.com/5aP2",
        ],
    },
    
    "opera" : {
        "title" : "opera",
        "links" : [
            "https://sptfy.com/9u1p",
            "https://sptfy.com/qnXQ",
        ],
    },
    
    "pagan" : {
        "title" : "pagan",
        "links" : [
            "https://sptfy.com/dG9F",
            "https://sptfy.com/5c6z",
            "https://sptfy.com/5hTb",
            "https://sptfy.com/a69s",
            "https://sptfy.com/i0aq",
            "https://sptfy.com/i0fL",
            "https://sptfy.com/5rwo",
        ],
    },
    
    "political" : {
        "title" : "political",
        "links" : [
            "https://sptfy.com/9s4p",
        ],
    },
    
    "pop" : {
        "title" : "pop",
        "links" : [
            "https://sptfy.com/9u0E",
            "https://sptfy.com/hSiW",
            "https://sptfy.com/hSiX",
            "https://sptfy.com/9u1w",
            "https://sptfy.com/9iKS",
            "https://sptfy.com/9oXn",
            "https://sptfy.com/5e1v",
            "https://sptfy.com/hT6R",
            "https://sptfy.com/9vDD",
            "https://sptfy.com/ivLQ",
        ],
    },
    
    "post-hardcore" : {
        "title" : "post-hardcore",
        "links" : [
            "https://sptfy.com/9u0d",
            "https://sptfy.com/9iKO",
            "https://sptfy.com/5c6y",
            "https://sptfy.com/5ezs",
            "https://sptfy.com/e7Bi",
        ],
    },

    "power" : {
        "title" : "power",
        "links" : [
            "https://sptfy.com/5hR7",
            "https://sptfy.com/9u0f",
            "https://sptfy.com/9u0h",
            "https://sptfy.com/9u0n",
            "https://sptfy.com/9Xg4",
            "https://sptfy.com/9u0B",
            "https://sptfy.com/hSiY",
            "https://sptfy.com/ejVF",
            "https://sptfy.com/dG9X",
            "https://sptfy.com/qUjL",
            "https://sptfy.com/iugS",
            "https://sptfy.com/dGa0",
            "https://sptfy.com/9u1d",
            "https://sptfy.com/9u1f",
            "https://sptfy.com/el8l",
            "https://sptfy.com/9u1o",
            "https://sptfy.com/9u1s",
            "https://sptfy.com/9u1v",
            "https://sptfy.com/eb6p",
            "https://sptfy.com/9u1w",
            "https://sptfy.com/5hSx",
            "https://sptfy.com/dGaM",
            "https://sptfy.com/hSjT",
            "https://sptfy.com/dGaT",
            "https://sptfy.com/9u20",
            "https://sptfy.com/9u27",
            "https://sptfy.com/9iKS",
            "https://sptfy.com/hH2U",
            "https://sptfy.com/9ivQ",
            "https://sptfy.com/574h",
            "https://sptfy.com/9mY3",
            "https://sptfy.com/9n6u",
            "https://sptfy.com/9nFN",
            "https://sptfy.com/hNfp",
            "https://sptfy.com/5du2",
            "https://sptfy.com/5hT9",
            "https://sptfy.com/9u2c",
            "https://sptfy.com/5hhn",
            "https://sptfy.com/5hhk",
            "https://sptfy.com/9u2e",
            "https://sptfy.com/9u2g",
            "https://sptfy.com/5ijV",
            "https://open.spotify.com/album/2WzWIsWJtI5n2PWK79PxGC",
            "https://sptfy.com/5jtk",
            "https://sptfy.com/5jH1",
            "https://sptfy.com/9vQ8",
            "https://sptfy.com/dIdQ",
            "https://sptfy.com/5k3O",
            "https://sptfy.com/hV5P",
            "https://sptfy.com/5noU",
            "https://sptfy.com/5ocH",
            "https://sptfy.com/5r48",
            "https://sptfy.com/5r65",
            "https://sptfy.com/5uvt",
            "https://sptfy.com/icnJ",
            "https://sptfy.com/e44a",
        ],
    },
    
    "progressive" : {
        "title" : "progressive",
        "links" : [
            "https://sptfy.com/9u0u",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/hSjS",
            "https://sptfy.com/9u21",
            "https://sptfy.com/9iKL",
            "https://sptfy.com/9ofC",
            "https://sptfy.com/e7Bi",
            "https://sptfy.com/5hhn",
            "https://sptfy.com/9u2e",
            "https://sptfy.com/9vX9",
            "https://sptfy.com/9yl1",
            "https://sptfy.com/qnXQ",
            "https://sptfy.com/i0ar",
            "https://sptfy.com/icnJ",
        ],
    },
    
    "punk" : {
        "title" : "punk",
        "links" : [
            "https://sptfy.com/hSiQ",
            "https://sptfy.com/duTR",
            "https://sptfy.com/9oXn",
            "https://sptfy.com/9s4p",
            "https://sptfy.com/e9wQ",
            "https://sptfy.com/9Xd2",
            "https://sptfy.com/hT6R",
            "https://sptfy.com/9vDD",
        ],
    },
    
    "rapcore" : {
        "title" : "rapcore",
        "links" : [
            "https://sptfy.com/hH2O",
            "https://sptfy.com/5aP2",
        ],
    },
    
    "remaster" : {
        "title" : "remaster",
        "links" : [
            "https://sptfy.com/ej5K",
        ],
    },
    
    "rock" : {
        "title" : "rock",
        "links" : [
            "https://sptfy.com/9u0E",
            "https://sptfy.com/dG9J",
            "https://sptfy.com/hSiQ",
            "https://sptfy.com/hSiW",
            "https://sptfy.com/efQC",
            "https://sptfy.com/hSiX",
            "https://sptfy.com/9u1g",
            "https://sptfy.com/9Xg8",
            "https://sptfy.com/9u1v",
            "https://sptfy.com/9u1N",
            "https://sptfy.com/dGaT",
            "https://sptfy.com/e9wQ",
            "https://sptfy.com/e7Bi",
            "https://sptfy.com/9Xd2",
            "https://sptfy.com/9u20",
            "https://sptfy.com/duTR",
            "https://sptfy.com/9iKO",
            "https://sptfy.com/hH2O",
            "https://sptfy.com/duTK",
            "https://sptfy.com/9oXn",
            "https://sptfy.com/5e1v",
            "https://sptfy.com/5ezs",
            "https://sptfy.com/9s4r",
            "https://sptfy.com/9s4p",
            "https://sptfy.com/5hho",
            "https://sptfy.com/5hhl",
            "https://sptfy.com/9u5d",
            "https://sptfy.com/5ijV",
            "https://sptfy.com/hT6R",
            "https://sptfy.com/5jtk",
            "https://sptfy.com/9vDD",
            "https://sptfy.com/9vX9",
            "https://sptfy.com/9yl1",
            "https://sptfy.com/5q3g",
            "https://sptfy.com/5tut",
            "https://sptfy.com/i58n",
            "https://sptfy.com/ivLQ",
        ],
    },
    
    "ska" : {
        "title" : "ska",
        "links" : [
            "https://sptfy.com/9vDD",
        ],
    },

    "spanish" : {
        "title" : "spanish",
        "links" : [
            "https://sptfy.com/5hR7",
            "https://sptfy.com/9u0i",
            "https://sptfy.com/9n6u",
            "https://sptfy.com/a4fR",
        ],
    },
    
    "speed" : {
        "title" : "speed",
        "links" : [
            "https://sptfy.com/dG9X",
            "https://sptfy.com/hSjJ",
            "https://sptfy.com/hSjN",
            "https://sptfy.com/hH2U",
            "https://sptfy.com/5hhp",
            "https://sptfy.com/hZ2t",
            "https://sptfy.com/5q3g",
        ],
    },
    
    "symphonic" : {
        "title" : "symphonic",
        "links" : [
            "https://sptfy.com/9u0h",
            "https://sptfy.com/9u0o",
            "https://sptfy.com/9u0s",
            "https://sptfy.com/dGa0",
            "https://sptfy.com/9u1f",
            "https://sptfy.com/9u1m",
            "https://sptfy.com/9u1p",
            "https://sptfy.com/5hSx",
            "https://sptfy.com/dGaM",
            "https://sptfy.com/9u23",
            "https://sptfy.com/qUjL",
            "https://sptfy.com/9TE5",
            "https://sptfy.com/9u25",
            "https://sptfy.com/ed3S",
            "https://sptfy.com/duTT",
            "https://sptfy.com/duTP",
            "https://sptfy.com/9nFN",
            "https://sptfy.com/9u28",
            "https://sptfy.com/5hT9",
            "https://sptfy.com/5hhn",
            "https://sptfy.com/9u52",
            "https://sptfy.com/9u5d",
            "https://open.spotify.com/album/2WzWIsWJtI5n2PWK79PxGC",
            "https://sptfy.com/5jtk",
            "https://sptfy.com/5jH1",
            "https://sptfy.com/9vQ8",
            "https://sptfy.com/9vX9",
            "https://sptfy.com/dIdQ",
            "https://sptfy.com/hV5P",
            "https://sptfy.com/9yl1",
            "https://sptfy.com/5ocH",
            "https://sptfy.com/qnXQ",
            "https://sptfy.com/dP5d",
            "https://sptfy.com/dP7b",
            "https://sptfy.com/5yhu",
        ],
    },
    
    "technical" : {
        "title" : "technical",
        "links" : [
            "https://sptfy.com/hSjS",
            "https://sptfy.com/hSjZ",
            "https://sptfy.com/9u29",
            "https://sptfy.com/9vK1",
        ],
    },
    
    "thrash" : {
        "title" : "thrash",
        "links" : [
            "https://sptfy.com/5hS2",
            "https://sptfy.com/9u1d",
            "https://sptfy.com/9u1C",
            "https://sptfy.com/dGaO",
            "https://sptfy.com/hSjS",
            "https://sptfy.com/hSk0",
            "https://sptfy.com/9u1Z",
            "https://sptfy.com/9iKL",
            "https://sptfy.com/dzOO",
            "https://sptfy.com/9sKW",
            "https://sptfy.com/5hhp",
            "https://sptfy.com/hZ2t",
            "https://sptfy.com/5q3g",
            "https://sptfy.com/dS5m",
            "https://sptfy.com/5urr",
            "https://sptfy.com/e0ed",
        ],
    },
    
    "throwback" : {
        "title" : "throwback",
        "links" : [
            "https://sptfy.com/5hR7",
            "https://sptfy.com/5hR8",
            "https://sptfy.com/dG9L",
            "https://sptfy.com/hSiO",
            "https://sptfy.com/hSiX",
            "https://sptfy.com/9u1h",
            "https://sptfy.com/9u27",
            "https://sptfy.com/9w5X",
            "https://sptfy.com/hV5P",
            "https://sptfy.com/i0ar",
            "https://sptfy.com/5qmL",
            "https://sptfy.com/dP5d",
            "https://sptfy.com/5zcQ",
        ],
    },
    
    "trance/dnb" : {
        "title" : "trance/dnb",
        "links" : [
            "https://sptfy.com/9u0A",
            "https://sptfy.com/ec1d",
        ],
    },
    
    "viking" : {
        "title" : "viking",
        "links" : [
            "https://sptfy.com/9u0y",
            "https://sptfy.com/dG9F",
            "https://sptfy.com/hSiY",
            "https://sptfy.com/dGa0",
            "https://sptfy.com/9u1o",
            "https://sptfy.com/dGaV",
            "https://sptfy.com/9u25",
            "https://sptfy.com/9u27",
            "https://sptfy.com/5c6z",
            "https://sptfy.com/5c6x",
            "https://sptfy.com/9u28",
            "https://sptfy.com/5hTb",
            "https://sptfy.com/9u2e",
            "https://sptfy.com/5oD8",
            "https://sptfy.com/i0aq",
            "https://sptfy.com/5r48",
            "https://sptfy.com/ej6w",
        ],
    },

}
